### ISSUE TITLE
New category suggestion: Code Smell

### ISSUE THREAD

**Issue by andyw8** [codeclimate/spec#16]
I'm currently working on a CodeClimate engine for [reek](https://github.com/troessner/reek) and I'm having some trouble deciding which category (or categories) the issues should map to.

Might there be a case for adding new category of 'Code Smell'?

**Comment by wfleming** [comment]
Hi @andyw8,

I think we would consider "Code Smell" to be a higher level category that includes existing categories like "Style" & "BugRisk". I know the category names aren't always descriptive enough by themselves, and I'm sorry we still haven't fleshed out the "TODO describe me" bits in that section of the spec yet.

Looking through reek's smell classes, I think they can fit fairly well in the existing categories. For example, things like `TooManyInstanceVariables` would be "Complexity", `DuplicateMethodCall` would be "Duplication", `ModuleInitialize` might be a "BugRisk", and a lot of other ones are probably best suited to "Style".

It might also be helpful for you to glance at the mappings we use for our [Rubocop engine](https://github.com/codeclimate/codeclimate-rubocop/blob/master/lib/cc/engine/category_parser.rb), which maps some of Rubocop's smell categories to Code Climate categories.

Hopefully that helps you move forward. If there are other smell types you still aren't sure about or think don't fit in existing categories, let me know. It'll be great to see a reek engine get done!

**Comment by andyw8** [comment]
Thanks for the feedback @wfleming. I'll look at the list of smells and see how I can best map them.
