### ISSUE TITLE
Why is there no language pack for Static languages like Java?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [codeclimate/spec#21]
Is you platform able to do something like this? I love you UI and the fabulous GitHub integration. I would love to get some people working on an port for the Salesforce.com Apex language (mix of Java and .net) but fear that you Engine is different from platforms like [SonarCube](www.sonarqube.org) where [this has been done](http://www.code-scan.com/overview/installing/)

**Comment by mrb** [comment]
@up2go-rsoesemann Hey there! Would you mind shooting me an email at `mrb@codeclimate.com` ? I'd love to talk about this!
