### ISSUE TITLE
Break out the reporting format spec

### ISSUE THREAD

**Issue by fulldecent** [codeclimate/spec#31]
Right now this spec is for making machines to do static analysis.

But the input and output formats can apply to a MUCH wider audience.

I have merged a standard I was working on to be compatible with this spec AND it also supports:

 * Static code analyzers
  * Code linters
  * Code style checkers
  * Minification checkers
 * Other static analyzers
  * Image metadata checkers
  * Image compression checkers
  * Spelling checkers
  * Grammar checkers
  * Digital signature verification
 * Dynamic code analysis
  * Unit tests (logic tests)
  * Automated UI tests
  * Continuous integration tests
 * Volatile testing
  * Link checkers
  * Package manager version checkers (requirement to use latest upstream versions)
  * Deployment testing (dry run)
 * Manual testing
  * Manual inspection
  * Manual walkthroughs
  * Customer feedback

It is at https://github.com/fulldecent/structured-acceptance-test

It you want to help change the world, please let me know and we can get together with this.

**Comment by fulldecent** [comment]
This may be an anti-pattern, but if the input format was also a separate specification (I'm not recommending it now) then you could replace engines with single line scripts:

    my-tool --sasr-output --sasr-input configfile

That would be compatible with one of my tools which, for example, runs on Travis and requires network access.

Again, I know that does not meet your business goals. However, it may be easier to have every static analysis tool support an interoperable `sasr` mode than to create docker images around each tool. And of course, once a tool is `sasr` compatible, then it will work with a generic sasr-code climate engine.

**Comment by fulldecent** [comment]
The latest commit https://github.com/fulldecent/structured-acceptance-test/commit/d30afa6118c58e901e77a7c62b6c25ee94eac3ea now specifies notes and extra restrictions for Code Climate.

**Comment by mrb** [comment]
@fulldecent We're scheduled to chat today - we can discuss this then!
