### ISSUE TITLE
Hello world implementation

### ISSUE THREAD

**Issue by fulldecent** [codeclimate/spec#36]
I have a lot to contribute to this project but I know NOTHING about Docker or Ruby or Code Climate. But I know how to do static analysis, so I hope you can help overcome these barriers to contribute.

Please explain to me like I'm stupid (because I am) how I can create and run a spec which checks for this very simple rule:

 > The source code must not contain: `a`, `e`, `i`, `o` or `u`

**Comment by ABaldwinHunter** [comment]
Hi @fulldecent. Thanks for your interest. Definitely explore the engine [SPEC](https://github.com/codeclimate/spec/blob/master/SPEC.md) which has a detailed explanation of what an engine is and how to set one up.

To get started with docker, check out this [blog post](http://blog.scottlowe.org/2014/03/11/a-quick-introduction-to-docker/) for an intro, and then go ahead and [install the docker toolbox and docker-machine](https://docs.docker.com/mac/step_one/) on whatever system you're using. 

The [fixme](https://github.com/codeclimate/codeclimate-fixme) engine was written to find target strings in source code, and provides a simple engine example. It actually can already do what you described - just change strings from `TODO, FIXME...` ... to `a, b, ...`. I might start there. Im bocca al lupo!

**Comment by fulldecent** [comment]
Thank you. I will look into this, but I hope we can turn this into a documentation part of this project.

**Comment by fulldecent** [comment]
This is also related to https://github.com/codeclimate/spec/issues/31 because that will allow us to support MANY more engines.
