### ISSUE TITLE
Remove fingerprint

### ISSUE THREAD

**Issue by fulldecent** [codeclimate/spec#40]
`fingerprint` is an opaque and redundant data element.

It can be calculated automatically be the Spec consumer by making a hash of the relevant issue contents. Its inclusion in the specification is an implementation detail of the Code Climate consumer. It should be removed.

----

Note: Structured Acceptance Test Output includes repeatability guarantees which is a stronger concept than fingerprints. It is discussed at https://github.com/fulldecent/structured-acceptance-test/blob/master/Stat-Output.md

**Comment by mrb** [comment]
@fulldecent Thanks for your feedback here - for the time being, our system relies heavily on fingerprints. We'll keep a more flexible approach in mind if we need to reconsider.
