### ISSUE TITLE
Docker "MAINTAINER" instruction is deprecated

### ISSUE THREAD

**Issue by michaelherold** [codeclimate/spec#46]
Docker deprecated the "MAINTAINER <name>" instruction in favor of "LABEL maintainer <name>". Perhaps we should update the CodeClimate Engine Spec to reflect this change in thinking?

See: https://docs.docker.com/engine/reference/builder/#/maintainer-deprecated

**Comment by dblandin** [comment]
Definitely! I'll see about making that spec change 👌

**Comment by dblandin** [comment]
Updated in #53. Thanks for the suggestion!
