### ISSUE TITLE
Keep a change log

### ISSUE THREAD

**Issue by michaelherold** [codeclimate/spec#54]
It would be nice if there was a change log for the spec. This would help to keep up-to-date on the spec version you're using in an engine.

I'm partial to the [keepachangelog.com format](http://keepachangelog.com/en/0.3.0/).

**Comment by pbrisbin** [comment]
Thanks for the suggestion, I agree. Our preferred format is _mostly_ like that one, so I think you'll be happy with it. I will keep this on my plate and back-fill a `CHANGELOG.md` when I'm able -- I don't know that we've released more than the first version so far, but will certainly check.
